services:
  Instance1:
    container_name: Instance1
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    volumes:
      - ./shairport-sync-instance1.conf:/etc/shairport-sync.conf
      - /var/run/pulse/native:/tmp/pulseaudio.socket
    networks:
      spsnet_shared:
      spsnet:
        ipv4_address: 192.168.1.101
  Instance2:
    container_name: Instance2
    image: mikebrady/shairport-sync:latest
    restart: unless-stopped
    volumes:
      - ./shairport-sync-instance2.conf:/etc/shairport-sync.conf
      - /var/run/pulse/native:/tmp/pulseaudio.socket
    networks:
      spsnet_shared:
      spsnet:
        ipv4_address: 192.168.1.102
networks:
  spsnet:
    name: spsnet
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
  spsnet_shared:
    name: spsnet_shared
    driver: bridge
